// const Sdata = {
//   shopItems: [
//     {
//       id: 1,
//       cover: "./images/shops/shop-1.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
      
//     },
//     {
//       id: 2,
//       cover: "./images/shops/shop-16.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
      
//     },
//     {
//       id: 3,
//       cover: "./images/shops/shop-31.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
      
//     },
//     {
//       id:4,
//       cover: "./images/shops/shop-2.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
      
//     },
//     {
//       id: 5,
//       cover: "./images/shops/shop-17.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
      
//     },
//     {
//       id: 6,
//       cover: "./images/shops/shop-32.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
      
//     },
    
//     {
//       id: 7,
//       cover: "./images/shops/shop-3.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
      
//     },
//     {
//       id: 8,
//       cover: "./images/shops/shop-18.png",
//       name: "Vivo android one",
//       price: "120",
//       discount: "10",
//       category: "men",
//     },
//     {
//       id: 9,
//       cover: "./images/shops/shop-33.png",
//       name: "Sony Light",
//       price: "20",
//       discount: "50 ",
//       category: "kids",

//     },
//     {
//       id: 10,
//       cover: "./images/shops/shop-4.png",
//       name: "Iphone",
//       price: "999",
//       discount: "10 ",
//       category: "women",

//     },
//     {
//       id: 11,
//       cover: "./images/shops/shop-19.png",
//       name: "Ceats wireless earphone",
//       price: "80",
//       discount: "20 ",
//       category: "men",

//     },
//     {
//       id: 12,
//       cover: "./images/shops/shop-34.png",
//       name: "Redimi Phone",
//       price: "400",
//       discount: "20 ",
//       category: "kids",

//     },
//     {
//       id: 13,
//       cover: "./images/shops/shop-5.png",
//       name: "Xeats Bluetooth earphones",
//       price: "60",
//       discount: "5 ",
//       category: "women",

//     },
//     {
//       id: 14,
//       cover: "./images/shops/shop-20.png",
//       name: "Airpod",
//       price: "120",
//       discount: "10",
//       category: "men",

//     },
//     {
//       id: 15,
//       cover: "./images/shops/shop-35.png",
//       name: "Silver Cap",
//       price: "5",
//       discount: "2",
//       category: "kids",
//     },
//     {
//       id: 16,
//       cover: "./images/shops/shop-6.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "wommen",
//     },
//     {
//       id: 17,
//       cover: "./images/shops/shop-7.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
//     },
//     {
//       id: 18,
//       cover: "./images/shops/shop-8.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
//     },
//     {
//       id: 19,
//       cover: "./images/shops/shop-9.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
//     },
//     {
//       id: 20,
//       cover: "./images/shops/shop-10.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
//     },
//     {
//       id: 21,
//       cover: "./images/shops/shop-11.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
//     },
//     {
//       id: 22,
//       cover: "./images/shops/shop-12.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
//     },
//     {
//       id: 23,
//       cover: "./images/shops/shop-13.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
//     },
//     {
//       id: 24,
//       cover: "./images/shops/shop-14.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
//     },
//     {
//       id: 25,
//       cover: "./images/shops/shop-15.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "women",
//     },
//     {
//       id: 26,
//       cover: "./images/shops/shop-21.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
//     },
//     {
//       id: 27,
//       cover: "./images/shops/shop-22.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
//     },
//     {
//       id: 28,
//       cover: "./images/shops/shop-23.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
//     },
//     {
//       id: 29,
//       cover: "./images/shops/shop-24.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
//     },
//     {
//       id: 30,
//       cover: "./images/shops/shop-25.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
//     },
//     {
//       id: 31,
//       cover: "./images/shops/shop-26.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
//     },
   
//     {
//       id: 33,
//       cover: "./images/shops/shop-28.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
//     },
//     {
//       id: 34,
//       cover: "./images/shops/shop-29.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
//     },
//     {
//       id: 35,
//       cover: "./images/shops/shop-30.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "men",
//     },

//     {
//       id: 36,
//       cover: "./images/shops/shop-36.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
//     },
//     {
//       id: 37,
//       cover: "./images/shops/shop-37.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
//     },
//     {
//       id: 38,
//       cover: "./images/shops/shop-38.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
//     },
//     {
//       id: 39,
//       cover: "./images/shops/shop-39.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
//     },
//     {
//       id: 40,
//       cover: "./images/shops/shop-40.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
//     },
//     {
//       id: 41,
//       cover: "./images/shops/shop-41.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
//     },
//     {
//       id: 42,
//       cover: "./images/shops/shop-42.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
//     },
//     {
//       id: 43,
//       cover: "./images/shops/shop-43.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
//     },
//     {
//       id: 44,
//       cover: "./images/shops/shop-44.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
//     },
//     {
//       id: 45,
//       cover: "./images/shops/shop-45.png",
//       name: "Mapple Earphones",
//       price: "180",
//       discount: "25",
//       category: "kids",
//     },
    
    

//   ],
// }
// export default Sdata



const Sdata = {
  shopItems:[
 {
   id: 1,
   description: 'T-shirt en coton léger, confortable, disponible en plusieurs tailles.',
   discount: 25,
   gender: 'women',
   imageUrl: './images/shops/shop-1.png',
   name: 'T-shirt en coton',
   price: 30,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 2,
   description: 'Jean slim pour femmes, coupe moderne, disponible en plusieurs couleurs.',
   discount: 25,
   gender: 'women',
   imageUrl: './images/shops/shop-2.png',
   name: 'Jean slim',
   price: 50,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 3,
   description: 'Robe d’été légère, parfaite pour les journées chaudes.',
   discount: 25,
   gender: 'women',
   imageUrl: './images/shops/shop-3.png',
   name: 'Robe d’été',
   price: 40,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 4,
   description: 'Veste en jean, un classique de la mode.',
   discount: 25,
   gender: 'women',
   imageUrl: './images/shops/shop-4.png',
   name: 'Veste en jean',
   price: 60,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 5,
   description: 'T-shirt à message, parfait pour un look décontracté.',
   discount: 25,
   gender: 'women',
   imageUrl: './images/shops/shop-5.png',
   name: 'T-shirt à message',
   price: 20,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 6,
   description: 'Jean skinny pour femmes, coupe ajustée et stretch.',
   discount: 25,
   gender: 'women',
   imageUrl: './images/shops/shop-6.png',
   name: 'Jean skinny',
   price: 45,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 7,
   description: 'Veste en cuir, idéale pour les soirées fraîches.',
   discount: 25,
   gender: 'women',
   imageUrl: './images/shops/shop-7.png',
   name: 'Veste en cuir',
   price: 120,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 8,
   description: 'Jupe en denim, confortable et stylée.',
   discount: 10,
   gender: 'women',
   imageUrl: './images/shops/shop-8.png',
   name: 'Jupe en denim',
   price: 25,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 9,
   description: 'Robe de soirée, élégante et chic.',
   discount: 50,
   gender: 'women',
   imageUrl: './images/shops/shop-9.png',
   name: 'Robe de soirée',
   price: 80,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 10,
   description: 'Sweat à capuche, confortable et chaud.',
   discount: 10,
   gender: 'women',
   imageUrl: './images/shops/shop-10.png',
   name: 'Sweat à capuche',
   price: 40,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 11,
   description: 'Chemise en lin, légère et respirante.',
   discount: 20,
   gender: 'women',
   imageUrl: './images/shops/shop-11.png',
   name: 'Chemise en lin',
   price: 35,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 12,
   description: 'Pantalon cargo pour hommes, pratique et stylé.',
   discount: 20,
   gender: 'men',
   imageUrl: './images/shops/shop-12.png',
   name: 'Pantalon cargo',
   price: 55,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 13,
   description: 'Chapeau de paille, idéal pour l’été.',
   discount: 5,
   gender: 'women',
   imageUrl: './images/shops/shop-13.png',
   name: 'Chapeau de paille',
   price: 15,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 14,
   description: 'Bermuda pour hommes, parfait pour les vacances.',
   discount: 10,
   gender: 'men',
   imageUrl: './images/shops/shop-14.png',
   name: 'Bermuda',
   price: 30,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 15,
   description: 'Casquette de sport, parfaite pour les activités extérieures.',
   discount: 2,
   gender: 'unisex',
   imageUrl: './images/shops/shop-15.png',
   name: 'Casquette de sport',
   price: 10,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 16,
   description: 'Pantalon de jogging confortable pour hommes.',
   discount: 15,
   gender: 'men',
   imageUrl: './images/shops/shop-16.png',
   name: 'Pantalon de jogging',
   price: 35,
   salesCount: 0,
   size: 'M',
   stock: 15,
   categoryId: 2
 },
 {
   id: 17,
   description: 'T-shirt léger pour hommes, parfait pour l’été.',
   discount: 10,
   gender: 'men',
   imageUrl: './images/shops/shop-17.png',
   name: 'T-shirt léger',
   price: 20,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 18,
   description: 'Robe chic pour femmes, idéale pour une soirée élégante.',
   discount: 50,
   gender: 'women',
   imageUrl: './images/shops/shop-18.png',
   name: 'Robe chic',
   price: 70,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 19,
   description: 'Short décontracté pour hommes, parfait pour l’été.',
   discount: 15,
   gender: 'men',
   imageUrl: './images/shops/shop-19.png',
   name: 'Short décontracté',
   price: 25,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 20,
   description: 'Sweat-shirt pour hommes, confortable et décontracté.',
   discount: 20,
   gender: 'men',
   imageUrl: './images/shops/shop-20.png',
   name: 'Sweat-shirt',
   price: 45,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 21,
   description: 'Pantalon de travail pour hommes, robuste et pratique.',
   discount: 30,
   gender: 'men',
   imageUrl: './images/shops/shop-21.png',
   name: 'Pantalon de travail',
   price: 60,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 22,
   description: 'T-shirt à manches longues pour hommes.',
   discount: 25,
   gender: 'men',
   imageUrl: './images/shops/shop-22.png',
   name: 'T-shirt à manches longues',
   price: 40,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 23,
   description: 'Casquette de baseball pour femmes, tendance et stylée.',
   discount: 15,
   gender: 'women',
   imageUrl: './images/shops/shop-23.png',
   name: 'Casquette de baseball',
   price: 25,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 24,
   description: 'Chemise à carreaux pour hommes, élégante et pratique.',
   discount: 20,
   gender: 'men',
   imageUrl: './images/shops/shop-24.png',
   name: 'Chemise à carreaux',
   price: 50,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 25,
   description: 'Jupe midi pour femmes, élégante et légère.',
   discount: 30,
   gender: 'women',
   imageUrl: './images/shops/shop-25.png',
   name: 'Jupe midi',
   price: 55,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 26,
   description: 'Polo pour hommes, matière respirante et coupe moderne.',
   discount: 15,
   gender: 'men',
   imageUrl: './images/shops/shop-26.png',
   name: 'Polo classique',
   price: 35,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 27,
   description: 'Blazer élégant pour femmes, idéal pour le bureau ou les soirées.',
   discount: 40,
   gender: 'women',
   imageUrl: './images/shops/shop-45.png',
   name: 'Blazer féminin',
   price: 90,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 28,
   description: 'Short en lin pour hommes, léger et confortable.',
   discount: 10,
   gender: 'men',
   imageUrl: './images/shops/shop-28.png',
   name: 'Short en lin',
   price: 28,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 29,
   description: 'Combinaison légère pour femmes, style urbain et pratique.',
   discount: 25,
   gender: 'women',
   imageUrl: './images/shops/shop-29.png',
   name: 'Combinaison été',
   price: 65,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 30,
   description: 'Manteau en laine pour hommes, chaud et élégant.',
   discount: 35,
   gender: 'men',
   imageUrl: './images/shops/shop-30.png',
   name: 'Manteau d’hiver',
   price: 150,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 31,
   description: 'Top sport pour femmes, matière respirante.',
   discount: 10,
   gender: 'women',
   imageUrl: './images/shops/shop-31.png',
   name: 'Top de sport',
   price: 22,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 32,
   description: 'Ceinture en cuir véritable pour hommes.',
   discount: 5,
   gender: 'men',
   imageUrl: './images/shops/shop-32.png',
   name: 'Ceinture en cuir',
   price: 40,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 33,
   description: 'Robe longue bohème, idéale pour l’été.',
   discount: 20,
   gender: 'women',
   imageUrl: './images/shops/shop-33.png',
   name: 'Robe bohème',
   price: 75,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 34,
   description: 'Pull en cachemire pour femmes, doux et chaud.',
   discount: 30,
   gender: 'women',
   imageUrl: './images/shops/shop-34.png',
   name: 'Pull en cachemire',
   price: 110,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 35,
   description: 'Veste bomber pour hommes, style urbain.',
   discount: 25,
   gender: 'men',
   imageUrl: './images/shops/shop-35.png',
   name: 'Veste bomber',
   price: 85,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 36,
   description: 'Sandales confortables pour femmes, talon plat.',
   discount: 10,
   gender: 'women',
   imageUrl: './images/shops/shop-36.png',
   name: 'Sandales été',
   price: 28,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 37,
   description: 'Costume complet pour hommes, cérémonie ou bureau.',
   discount: 40,
   gender: 'men',
   imageUrl: './images/shops/shop-37.png',
   name: 'Costume classique',
   price: 200,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 38,
   description: 'Legging sport pour femmes, stretch et confortable.',
   discount: 15,
   gender: 'women',
   imageUrl: './images/shops/shop-38.png',
   name: 'Legging de sport',
   price: 30,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 39,
   description: 'Chaussures de ville pour hommes, cuir noir.',
   discount: 20,
   gender: 'men',
   imageUrl: './images/shops/shop-39.png',
   name: 'Chaussures de ville',
   price: 95,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 40,
   description: 'Écharpe en laine, unisexe, plusieurs coloris.',
   discount: 10,
   gender: 'unisex',
   imageUrl: './images/shops/shop-40.png',
   name: 'Écharpe en laine',
   price: 18,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 41,
   description: 'Sac à main pour femmes, cuir synthétique.',
   discount: 15,
   gender: 'women',
   imageUrl: './images/shops/shop-41.png',
   name: 'Sac à main',
   price: 50,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
 {
   id: 42,
   description: 'Montre élégante pour hommes, étanche.',
   discount: 25,
   gender: 'men',
   imageUrl: './images/shops/shop-42.png',
   name: 'Montre classique',
   price: 120,
   salesCount: 0,
   size: 'M',
   stock: 10,
   categoryId: 2
 },
  {
     id: 43,
     description: 'Bottes en cuir pour femmes, talon moyen.',
     discount: 30,
     gender: 'women',
     imageUrl: './images/shops/shop-43.png',
     name: 'Bottes élégantes',
     price: 130,
     salesCount: 0,
     size: 'M',
     stock: 10,
     categoryId: 2
   },
   {
     id: 44,
     description: 'Cravate en soie pour hommes, motif moderne.',
     discount: 10,
     gender: 'men',
     imageUrl: './images/shops/shop-44.png',
     name: 'Cravate en soie',
     price: 25,
     salesCount: 0,
     size: 'M',
     stock: 10,
     categoryId: 2
   },
   {
     id: 45,
     description: 'Bijou fantaisie pour femmes, pendentif argenté.',
     discount: 5,
     gender: 'women',
     imageUrl: './images/shops/shop-45.png',
     name: 'Collier fantaisie',
     price: 15,
     salesCount: 0,
     size: 'M',
     stock: 10,
     categoryId: 2
   }
 ],
 }

 export default Sdata;